### ISSUE TITLE
Tag pseudo-releases?

### ISSUE THREAD

**Issue by carlocab** [facebookexperimental/edencommon#2]
Hi there,

I'm interested in packaging edencommon at Homebrew since Watchman now requires it (since https://github.com/facebook/watchman/commit/79180063553a24bf20c2bd863219a2d54ebad505). However, we have a policy of building only from tagged commits.

Would you consider tagging releases in this repository? The same scheme used in other facebook repositories (e.g. folly, wangle, watchman) of weekly tags seems simple enough and works reasonably well for us.

Thanks!

**Comment by fanzeyi** [comment]
Sure, let me enable it.

**Comment by fanzeyi** [comment]
I have enabled the weekly tagging bot for this repo. We should see a tag created for this repo next week. I also created a new tag for today. https://github.com/facebookexperimental/edencommon/releases/tag/v2022.08.15.00

I'll close this issue next week when we see the tagging bot working.

**Comment by carlocab** [comment]
Thanks @fanzeyi!

This seems to be working now.
