### ISSUE TITLE
Shared library name "libutils.so" is too generic

### ISSUE THREAD

**Issue by thesamesam** [facebookexperimental/edencommon#3]
After packaging edencommon in Gentoo for Watchman, we had a report of a file collision (https://bugs.gentoo.org/865111) with dev-ros/openslam_gmapping. The colliding file is `/usr/lib64/libutils.so`.

Could the shared library be renamed, given edencommon is so new?

**Comment by fanzeyi** [comment]
Sorry about it. `libutils.so` is a bit too generic. 😅

I'll put up a diff to fix this.

**Comment by thesamesam** [comment]
Fantastic, thanks for addressing both of those bugs real quick @fanzeyi!
